-- Novas fases: Rascunho → Submetido → Validação e pagamento → Aprovado → Em produção → Finalizado → Entregue (+ Cancelado)

ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT;

ALTER TABLE "orders" ALTER COLUMN "status" TYPE TEXT USING ("status"::text);

UPDATE "orders" SET "status" = CASE "status"
  WHEN 'DRAFT' THEN 'DRAFT'
  WHEN 'SUBMITTED' THEN 'SUBMITTED'
  WHEN 'AWAITING_DESIGNER' THEN 'VALIDATION_PAYMENT'
  WHEN 'CLIENT_EDITING' THEN 'VALIDATION_PAYMENT'
  WHEN 'AWAITING_CLIENT' THEN 'VALIDATION_PAYMENT'
  WHEN 'ADJUSTMENTS_REQUESTED' THEN 'VALIDATION_PAYMENT'
  WHEN 'APPROVED_FOR_PRODUCTION' THEN 'APPROVED'
  WHEN 'IN_QUEUE' THEN 'IN_PRODUCTION'
  WHEN 'PRINTING' THEN 'IN_PRODUCTION'
  WHEN 'FINISHING' THEN 'FINISHED'
  WHEN 'DELIVERED' THEN 'DELIVERED'
  WHEN 'CANCELLED' THEN 'CANCELLED'
  WHEN 'BLOCKED' THEN 'IN_PRODUCTION'
  WHEN 'SHIPPED' THEN 'DELIVERED'
  ELSE 'VALIDATION_PAYMENT'
END;

DROP TYPE IF EXISTS "OrderStatus";

CREATE TYPE "OrderStatus" AS ENUM (
  'DRAFT',
  'SUBMITTED',
  'VALIDATION_PAYMENT',
  'APPROVED',
  'IN_PRODUCTION',
  'FINISHED',
  'DELIVERED',
  'CANCELLED'
);

ALTER TABLE "orders"
  ALTER COLUMN "status" TYPE "OrderStatus"
  USING ("status"::"OrderStatus");

ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'DRAFT'::"OrderStatus";
